src/app/modules/item/item/item.component.html, src/app/modules/item/item/item.component.ts
Replace imperative use of `ObservableMedia.isActive` by an observable based on
`ObservableMedia.asObservable` combined with an `AsyncPipe`. The `AsyncPipe` take care of the change
detection.
fix #153
=> fix(item): use observable to react to ObservableMedia change

src/app/modules/common-components/amount-input/amount-input.component.html, src/app/modules/common-components/amount-input/amount-input.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/ja.json
Add tooltip that show the amount of missing items required to reach the total. The tooltip is shown
when hovering the native input field.
fix #145
=> feat(item): add tooltip showing the amount of missing items

src/app/app.component.scss
Social fabs were black on teal themes. Now they're not. I hope.
=> fix: black social fabs (#221)

src/app/modules/item/item/item.component.html
I suppose /isearch value should be quoted. It behaves wrong for items that name contains more than one word.
=> fix: isearch value quotes

src/app/pages/simulator/components/macro-popup/macro-popup.component.html
Adding a linebreak element for each macro action fixes an firefox issue where linebreaks were not present when copying macros.
=> fix: fixes missing linebreaks when copying macro from firefox

src/app/pages/simulator/components/macro-popup/macro-popup.component.html
Cross-class skill setup macro was also missing line-breaks when copying from Firefox.
=> fix: missing linebreaks in cross-class setup macro

src/app/pages/profile/profile/profile.component.ts, src/app/pages/profile/stats-edit-popup/stats-edit-popup.component.html, src/app/pages/profile/stats-edit-popup/stats-edit-popup.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json
Adds a "save for all" button, allowing users to quickly save the stats for one gearset across all gearsets. Resolves #418
=> feat: apply stats to all crafts button

src/app/model/list/app-user.ts, src/app/model/other/default-consumables.ts, src/app/pages/simulator/components/simulator/simulator.component.html, src/app/pages/simulator/components/simulator/simulator.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json
Adds the ability to save a rotation's consumables as default. When a new
rotation is created, these consumables will automatically be populated.
TODO: Currently setting defaults for every single rotation. :(
Resolves #426
=> feat(simulator): default consumables WIP

src/app/pages/simulator/components/simulator/simulator.component.ts
When a player is a specialist, they receive a bonus of 20 to both craftsmanship and control. This feature will reflect that bonus in the crafting simulator.
=> feat: add specialist stat bonus

src/app/pages/simulator/components/macro-popup/macro-popup.component.html, src/app/pages/simulator/components/macro-popup/macro-popup.component.scss, src/app/pages/simulator/components/macro-popup/macro-popup.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json
Adds a numeric input to the in-game macro generator that allows users to specify an extra wait value. This value is added to all occurrences of <wait.x> in the macro. Also adds limits to the notification # to keep it from going out of bounds.
Resolves #428
=> feat(simulator): add custom delay offset to apply to macro

src/app/pages/simulator/components/simulator/simulator.component.html, src/app/pages/simulator/components/simulator/simulator.component.ts
Fixes #450 where tooltips would remain hidden after reordering actions.
The bug appears to be a result of the rotation actions having both the
draggable and droppable directives. In this case, onDrop appears to
fire while onDragEnd does not.
=> fix: hidden action tooltips in simulator

src/app/modules/item/item/item.component.html, src/app/modules/item/item/item.component.ts, src/app/pages/list/list-details/list-details.component.ts
The UI style problems reported in #473 were a result of the mobile view
being rendered even though the user was on desktop. Added an explicit
check for desktop users to avoid rendering the mobile view. Also added
the missing row colors to mobile and removed a console log.
Resolves #473
=> fix: List UI style problems on small screens

src/app/pages/simulator/components/custom-simulator-page/custom-simulator-page.component.html, src/app/pages/simulator/components/custom-simulator-page/custom-simulator-page.component.ts, src/app/pages/simulator/components/simulator/simulator.component.html, src/app/pages/simulator/components/simulator/simulator.component.ts
Fixes custom rotations so that the selected job saves properly.
Previously, this was being overridden in the simulator's ngOnInit.
Also fixes consumables and actions which were not being saved at all.
Fixes #455
=> fix: selected job not saved in custom rotation

src/app/pages/commission-board/commission-creation-popup/commission-creation-popup.component.html, src/app/pages/commission-board/commission-creation-popup/commission-creation-popup.component.ts, src/app/pages/commission-board/commission-panel/commission-panel.component.ts, src/app/pages/list/list-details/list-details.component.ts, src/app/pages/recipes/recipes/recipes.component.html, src/app/pages/recipes/recipes/recipes.component.ts
Adds a commission button to the Items search that allows a user to
quickly create a commission for that single item. Updates the commission
dialog to allow suppression of the list warning since it does not apply
in this case. Updates the flow for deleting a commission so that the
list is destroyed if it was a quick commission.
Resolves #490
=> feat: quick commission button on search results

src/app/modules/item/item/item.component.html
Adds missing recipeId parameter to simulator links for list items,
ensuring that the recipe with the proper job is loaded. This bug
was an extension of #401 that applied to the simulator links on the
final products.
=> fix: list recipe simulator links

src/app/core/api/garland-tools.service.ts, src/app/model/garland-tools/job-category.ts, src/app/model/garland-tools/venture.ts, src/app/model/list/garland-tools-data.ts, src/app/modules/item/item/item.component.ts, src/app/modules/item/venture-details-popup/venture-details-popup.component.html, src/app/modules/item/venture-details-popup/venture-details-popup.component.scss, src/app/modules/item/venture-details-popup/venture-details-popup.component.ts, src/app/pipes/job-abbr.pipe.ts
Adds significantly more details to the venture details popup, including
required level, venture name, and amount of items yielded. Introduces
new JobCategory and Venture interfaces for the Garland Tools data, as
well as functions for retrieving this information from the GT service.
Resolves #315
=> feat: show levels for retainer ventures

src/app/model/list/list.ts, src/app/pages/list/total-price-popup/total-price-popup.component.html, src/app/pages/list/total-price-popup/total-price-popup.component.scss, src/app/pages/list/total-price-popup/total-price-popup.component.ts
Displays a cost range where applicable, from the cost for all NQ mats to
the cost for all HQ mats. A single cost value is displayed for materials
that cannot be purchased as HQ. Fixed up change detection and console log.
Resolves #442
=> feat: add HQ material cost to total price popup

src/app/modules/item/venture-details-popup/venture-details-popup.component.ts, src/app/pages/simulator/components/simulator/simulator.component.html
Updates the venture amounts logic to handle cases where the amounts are present in the GT API but the required stats are not. Previously this failed and the venture level/job were not displayed.
Updates the change recipe button in the simulator to disable instead of being hidden.
=> refactor: list and simulator tweaks

src/app/modules/common-components/list-panel/list-panel.component.html, src/app/pages/lists/lists/lists.component.html
Moves the open button to the far left and the security & delete
buttons to the far right. This should better order the buttons from
most to least used. Also colors the delete button red, since it is
destructive.
=> refactor: list and workshop button order

src/app/pages/recipes/recipes/recipes.component.html, src/app/pages/recipes/recipes/recipes.component.scss
Striping odd rows instead of even rows. Lowered the opacity of the striping to provide a less harsh contrast, especially for light themes.
=> refactor: recipe search striping

src/app/model/other/default-consumables.ts, src/app/modules/pricing/pricing-row/pricing-row.component.html, src/app/modules/pricing/pricing-row/pricing-row.component.scss, src/app/modules/pricing/pricing-row/pricing-row.component.ts, src/app/modules/pricing/pricing.module.ts, src/app/modules/pricing/pricing.service.ts, src/app/modules/pricing/pricing/pricing.component.html, src/app/modules/pricing/pricing/pricing.component.ts, src/assets/i18n/en.json, src/assets/i18n/es.json, src/assets/i18n/fr.json
Resolves #515 by implementing the features 4 & 5 it requested. Features 1-3 already exist and are set to remain in place.
The cost of pre-crafts is now determined automatically by the sum of their materials costs. A checkbox has been added that will allow the users to select it and enter a custom amount if they wish to override this value.
Totals for each individual panel in pricing mode have been removed, as the spending logic has changed. Now instead of summing each of these totals, we recursively sum the costs of each material required for the final recipes. This also removes the "materials have cost" warning.
Adds automatic balancing to the item amounts. For example, if a recipe requires 8 of an item, you can have 5 NQ and 3 HQ. Increasing the NQ to 6 will automatically decrease the …
=> Updated pricing mode

src/app/pages/commission-board/commission-board.module.ts, src/app/pages/commission-board/commission-board/commission-board.component.ts, src/app/pages/commission-board/commission-panel/commission-panel.component.html, src/app/pages/commission-board/commission-panel/commission-panel.component.ts, src/app/pages/commission-board/history/history.component.ts, src/app/pages/commission-board/server-history/server-history.component.html, src/app/pages/commission-board/server-history/server-history.component.scss, src/app/pages/commission-board/server-history/server-history.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json
Adds another tab to the commission board where users can view the
previous commissions archived for their server. Updates the commission
panel to hide the Archived tag, since it is redundant. Updates the
archived commission fetch to query the status from Firestore and sort
the results in descending date order.
Resolves #519
=> feat: commission board history

src/app/pages/simulator/components/simulator/simulator.component.html, src/app/pages/simulator/components/simulator/simulator.component.ts
Change drag-and-drop logic to manually move part of the array between the old and new position.
Should also be a bit faster than 2 splices.
Closes #552
=> fix(simulator): Fix actions being placed into wrong spots

src/app/pages/simulator/components/rotations-page/rotations-page.component.html
The new rotation button was not displaying for guest users, where the
rotations observable was not returning data. The display of the new
rotation button should not be dependent on the rotations data, so it has
been moved outside of the div that was checking for it.
=> fix: new rotation button not displaying

src/app/pages/simulator/components/simulator/simulator.component.html, src/app/pages/simulator/components/simulator/simulator.component.scss, src/app/pages/simulator/components/simulator/simulator.component.ts
Displays the starting quality in the ingredients panel after HQ
ingredients have been selected. Also fixes a bug where new rotations
could not be saved.
Resolves #591
=> feat: starting quality

src/app/pages/simulator/components/simulator/simulator.component.html, src/app/pages/simulator/components/simulator/simulator.component.scss
Fixes incorrect flexing on consumable styles where the widths were incorrect and the placeholder text was not being displayed.
**Before:**
**After:**
=> fix: consumable styles

src/app/pages/simulator/components/custom-simulator-page/custom-simulator-page.component.ts, src/app/pages/simulator/components/simulator/simulator.component.html, src/app/pages/simulator/components/simulator/simulator.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/es.json, src/assets/i18n/fr.json, src/assets/i18n/ja.json
Adds a button to the Simulator page that allows users to convert a saved
custom rotation into a normal rotation. This is done by allowing the
user to search for a recipe to use for the rotation, and then saving
that item/recipe with the rotation so it is opened like a normal one.
Resolves #609
=> feat: convert custom rotation to normal rotation

src/app/pages/simulator/model/actions/quality/byregots-miracle.ts, src/index.html
Previously it was adding a stack of Inner Quiet, but that should not be happening. The stacks should also be rounded up after the division.
=> Fix Byregot's Miracle

apps/client/src/app/pages/simulator/components/rotations-page/rotations-page.component.html, apps/client/src/app/pages/simulator/components/rotations-page/rotations-page.component.less, apps/client/src/app/pages/simulator/components/simulator/simulator.component.html, apps/client/src/app/pages/simulator/components/simulator/simulator.component.less
Reorganizes the configuration panels so that their apply buttons all line up nicely. Also makes some minor changes to various spacing and fixes the missing translation on the "New rotation" button.
=> refactor: align rotation configuration buttons

apps/client/src/app/pages/simulator/components/simulator/simulator.component.html, apps/client/src/app/pages/simulator/components/simulator/simulator.component.ts
This fixes the issue with drag-n-drop on the simulator.
In some cases the user is still unable to drop properly with error `ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.` but it seems like an unrelated issue from the library itself
=> fix(simulator): dragging the last action doesn't make it immovable

apps/client/src/app/pages/lists/list-import-popup/link-parser/ariyala-link-parser.ts
This causes incorrect materia calculations when using the option to assume the same melds accross multiple DoH/DoL jobs.
=> fix(ariyala): fix 'hands' slot incorrectly regarded as tool

package-lock.json, package.json
This patch restores market board upload functionality.
=> chore: Update node-machina-ffxiv to 2.19.5

apps/client/src/app/core/api/data.service.ts
Allows for copy item name direct from game to search box.
=> feat(search): Ignore HQ and Collectable symbols in search

apps/client/src/app/core/api/universalis.service.ts
Tax rates are world-dependent, so this field needs to be sent.
=> chore: Add world ID and uploader ID to tax rates upload

package.json
too lazy to type `npm run ng-high-memory serve --project=client` ;)
=> chore: add high memory start script

apps/client/src/app/core/api/universalis.service.ts
Just a matter of putting the packet information where it needs to go
=> fix: Correct world ID not changing for data uploads when appropriate

apps/client/src/app/core/api/data.service.ts
Check that a recipe exists, and it craftable by any class, when searching for a recipe.
=> fix(search): Fix recipe search not showing any items in some cases

apps/client/src/assets/i18n/en.json, apps/client/src/assets/i18n/hr-HR.json, apps/client/src/assets/i18n/pt-BR.json, apps/client/src/assets/i18n/pt-PT.json, apps/client/src/assets/i18n/ru-RU.json, apps/client/src/assets/i18n/zh-CN.json
Noticed while using the Inventory Optimizer the grammar on the `CAN_BE_BOUGHT` English localization string wasn't quite right. This small change corrects that string across all localizations where the English string was in use.
* `npm test`: Pass
```
Chrome 78.0.3904 (Windows 10 0.0.0): Executed 11 of 11 SUCCESS (0.134 secs / 0.058 secs)
TOTAL: 11 SUCCESS
TOTAL: 11 SUCCESS
=============================== Coverage summary ===============================
Statements   : 50.27% ( 187/372 )
Branches     : 21.71% ( 33/152 )
Functions    : 36.51% ( 23/63 )
Lines        : 50% ( 176/352 )
================================================================================
```
* `npm e2e`: Consistent with `staging` branch.
```
Spec                                                Tests  Passing  Failing …
```
=> fix(optimizer): updated grammar in optimizer l10n

apps/client/src/app/core/api/universalis.service.ts, apps/client/src/app/core/electron/ipc.service.ts, desktop/machina.js
The history data is only a single packet, so it doesn't need a debounce. 
To handle a packet having no listings, the client needs to send an erase 
op for these items. This information is obtained from the search result 
packet.
=> chore: move history off debounce; fix zero-listing-case

apps/client/src/app/pages/db/item/item.component.ts
- Fixed gardening link refusing to connect, ffxiv gardening no longer supports HTTPS after switching webhosts. 
- Fixed gardening link showing up on item pages for items that do not come from gardening.
- Changed outdated mogboard link to universalis
=> Fix(db): Several link fixes

apps/client/src/app/pages/simulator/rotation-tips/tips/use-inner-quiet.ts
Inner Quiet should not be suggested when Trained Eye is used as the first step to max quality.
=> FIX: Don't suggest IQ when TE is used

apps/client/src/app/core/data-reporting/fishing-reporter.ts, desktop/machina.js, package-lock.json, package.json
This seems to fix the hanging on zone changes, and has all of Sapphire's latest opcodes as well. EventUnk0 and EventUnk1 have been renamed to EventPlay#.
This should all be tested to make sure the hanging fix works for everyone affected and that no more opcodes are missing.
=> chore: Update node-machina-ffxiv to 2.31.23

apps/client/src/app/pages/gearset/gearset-editor/gearset-editor.component.ts
Two issues addressed:
1. Removal of last materia in a piece of equipment was ignored. So that
materia could never be removed.
2. When adding or removing a materia, the Gearset Editor view was not
dynamically updating.
=> Gearsets: Fix materia change detection

.gitattributes, .vscode/launch.json, .vscode/tasks.json, apps/client/src/app/pages/inventory-optimizer/inventory-optimizer.module.ts, apps/client/src/app/pages/inventory-optimizer/inventory-optimizer/inventory-optimizer.component.html, apps/client/src/app/pages/inventory-optimizer/inventory-optimizer/inventory-optimizer.component.less, apps/client/src/app/pages/inventory-optimizer/inventory-optimizer/inventory-optimizer.component.ts, apps/client/src/app/pages/inventory-optimizer/optimizations/consolidate-stacks.ts, apps/client/src/app/pages/inventory-optimizer/optimizations/duplicates.ts, apps/client/src/app/pages/inventory-optimizer/optimizations/inventory-optimizer.ts, apps/client/src/assets/i18n/en.json
A new inventory optimizer that will suggest high-quality (HQ) stacks of
items that can have their quality lowered so that it can be joined with
an existing normal-quality (NQ) stack of that same type of item. This is
a very reliable way to free up inventory slots.
Because users may not want all stacks of items suggested, filtering is
provided by expansion. For example, if a user wants all items in
Heavensward and below suggested (Heavensward + A Realm Reborn), they
will select "Heavensward" from the filter select box. Items with HQ and
NQ stacks from Stormblood and Shadowbringers will *not* be selected in
this case because they are filtered out. You can also clear the filter
box (so it says "Pick Expansion") which completely disables filtering,
showing all available items in your …
=> Added "Consolidate Stacks" Inventory Optimizer

apps/client/src/app/core/electron/machina.service.ts
I checked that the opcode `RetainerInformation` works properly.
CN opcodes also have it.
It needs node-machina-ffxiv 2.32.7
Idk how to edit package.json 😅
I just modified from this commit https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/e7f25d01226715037a08432a5b63cf4e08b96def
I didn't touch `settings.service.ts` file, also I don't know... 
I don't know if I saved your trouble, but please do the rest! ❤️
=> chore(desktop): update retainers tracking for KR/CN players

.vscode/launch.json, .vscode/tasks.json, apps/client/src/app/pages/inventory-optimizer/optimizations/consolidate-stacks.ts
It was incorrectly identifying the NQ stack as the HQ stack. The
condition is reversed so that the HQ item is properly suggested.
Also reverted changes to files under `.vscode` to an earlier revision because recent changes were unintentional.
=> Fix consolidate stacks

apps/client/src/app/pages/levequests/levequests/levequests.component.html, apps/client/src/app/pages/levequests/levequests/levequests.component.less, apps/client/src/assets/i18n/en.json
Adds a "level range" label to the levequests page for clarity.
https://imgur.com/a/bbEWJWW
I touched a lot of html and css that I'm not too familiar with, please kick it back if I need to do things differently, or if this is unnecessary.
=> Feat(ux): levequest page "level range" label

apps/client/src/app/modules/list/+state/lists.facade.ts, apps/client/src/app/modules/list/model/list.ts
There are some edge cases in which this setting would not apply:
1. Creating a list from search results
2. Cloning another list
Now the setting for disabling HQ suggestions in lists works more
thoroughly.
Note that as part of this change, the "everyone" list property is also
more consistently handled.
=> fix: Disable HQ setting works more thoroughly

apps/client/src/app/pages/db/item/item.component.html
Fixes an issue on item pages where crafting level wasn't showing up.
Example: https://ffxivteamcraft.com/db/en/item/28718/Sublime-Solution
Scroll to the bottom in the "Used For" section, it only shows stars, not actual crafting level.
=> fix(ux): fixed crafting level showing on item page

apps/client/src/app/pages/inventory-optimizer/inventory-optimization.ts, apps/client/src/app/pages/inventory-optimizer/inventory-optimizer/inventory-optimizer.component.html, apps/client/src/app/pages/inventory-optimizer/inventory-optimizer/inventory-optimizer.component.less, apps/client/src/app/pages/inventory-optimizer/inventory-optimizer/inventory-optimizer.component.ts, apps/client/src/assets/i18n/en.json
Adds a button on each optimizer to hide it. Also adds a switch to the top of the optimizers page to show hidden optimizers, similar to the switch for showing ignored items/containers.
EDIT: Resolves #1432
=> feat(optimizers): Allowing hiding optimizers

apps/client/src/app/pages/simulator/abstract-simulation-page.ts, apps/client/src/app/pages/simulator/components/custom-simulator-page/custom-simulator-page.component.ts, apps/client/src/app/pages/simulator/components/simulation-share-popup/simulation-share-popup.component.ts, apps/client/src/app/pages/simulator/components/simulator-page/simulator-page.component.html, apps/client/src/app/pages/simulator/components/simulator-page/simulator-page.component.ts, apps/client/src/app/pages/simulator/components/simulator/simulator.component.html, apps/client/src/app/pages/simulator/components/simulator/simulator.component.ts, apps/client/src/app/pages/simulator/model/route-consumables.ts, apps/client/src/assets/i18n/en.json
feat: Share consumables with rotations
Now when including stats with crafting rotation links, the following
consumables are included:
* Selected Food
* Selected Medicine
* Up to two selected free company actions
This allows others that open your rotations via the link to see your
selected consumables. Previously the consumable stats were part of the
stats parameters which allowed others to add another food on top of it,
for example, effectively invalidating the simulation.
=> Share consumables with crafting rotation URLs

apps/client/src/app/pages/currency-spending/currency-spending/currency-spending.component.ts
Garland contains old shop listings which no longer exist in game.
Many items have simply been moved under a different shop listing,
resulting in the currency spending page showing duplicate items.
You can see the incorrect behavior by looking at `Yellow Crafters' Scrip` currency, as shown below:
=> fix(currency-spending): filter out shop listings with no npc

desktop/main.js
**Cause**:
`newVersionAvailable` is triggered **twice**, so as `updateDesktopApp`, `ipc.send('update:check')` and `autoUpdater.checkForUpdates()`
SquirrelUpdater will try to `touch` a lock file on startup. So when it's called the second time, lock is already opened by the first one and the exception is thrown.
Adding a lock to autoUpdater should prevent the second call and fix this error.
=> fix(desktop): fix "cannot acquire lock" error

apps/client/src/app/pages/desynth/desynth/desynth.component.ts
I don't know how to distinguish isDesynthesizable.
Salvage has deleted, but that column still seems to be valid.
It's just a conjecture, so it's not clear.
=> chore(desynth): delete invalid filter

apps/client/src/app/pages/alarms-page/alarms-page/alarms-page.component.html
Fixes bug reported in discord:
> Certain fishing hole pages cannot be loaded or shown properly from the alarms page
> Reproduction Steps
> 1.  search goldenfin
> 2. create quicklist of goldenfin
> 3. click set alarm button on list
> 4. go to alarm
> 5. click information button on goldenfin
> 6. It delivers you to https://ffxivteamcraft.com/db/en/map/-1/no-name
This change makes it so the map panel of the alarm card is not displayed in cases where there is no map to display.
The item reported in the above scenario probably _should_ have a valid map id, but that may be a data issue.
=> fix: do not display map in alarms with no mapId

apps/client/src/app/pages/alarms-page/alarms-page/alarms-page.component.html, apps/client/src/assets/i18n/de-DE.json, apps/client/src/assets/i18n/en.json, apps/client/src/assets/i18n/es-ES.json, apps/client/src/assets/i18n/fr-FR.json, apps/client/src/assets/i18n/hr-HR.json, apps/client/src/assets/i18n/ja-JP.json, apps/client/src/assets/i18n/ko-KR.json, apps/client/src/assets/i18n/nl-NL.json, apps/client/src/assets/i18n/pt-BR.json, apps/client/src/assets/i18n/pt-PT.json, apps/client/src/assets/i18n/ru-RU.json, apps/client/src/assets/i18n/zh-CN.json
This PR moves the buttons to delete a alarm-group into a dropdown.
fixes #1646
--
Unfortunately i was not sure how to translate some languages.
=> Move alarm group delete buttons into dropdown

apps/client/src/app/app.component.ts, apps/client/src/environments/patch-notes.ts, desktop/main.js
Addressed #1643 I feel like it's kind of scuff but I added somewhat proper zoom handling. The following checks for ``CTRL`` + ``=``(on number row) or ``+``(on numpad) to begin zoom in and sends it to main process.
```ts
// Scuff Zoom Handling
document.addEventListener("keydown", event => {
if (event.ctrlKey && [187, 107].includes(event.keyCode)) {
return this.ipc.send('zoom-in', event)
}
});
```
The main process is just gonna do simple maffs to increase zoomlevel.
```ts
ipcMain.on('zoom-in', () => {
var currentzoom = win.webContents.getZoomLevel()
win.webContents.setZoomLevel(currentzoom++)
})
```
=> feat: proper zoom handling in desktop app

apps/client/src/app/modules/list/list-details-panel/list-details-panel.component.ts, apps/client/src/app/pages/list-details/list-details/list-details.component.html
=> fix(list-details): large panels are now collapsed by default, instead of entire list

apps/client/src/app/pages/simulator/components/action/action.component.ts
The current choice of color for the state 'poor' has poor visibility against the default tooltip background color of #282828, which could cause issues for those with weak or color-compromised eyesight. 
I propose that the color 'purple' be changed to 'violet' instead. It matches the ingame color used for the state, as pictured here:
In addition, it has better legibility across the Teamcraft app without changing the aesthetic dramatically.
=> CHORE: Adjust color of step state 'poor'

apps/client/src/app/modules/list/item/alarm-button/alarm-button.component.html
=> fix(ux): fix empty tooltip for alarm button

apps/electron/src/pcap/packet-capture.ts
* This PR requires **pcap-ffxiv** being published and updated.
* I have no idea how to build electron app at local, so this is not fully tested. As a result this change may require extra testing.
Passes `localOpcodesPath: join(process.resourcesPath, 'localOpcodes')` to **pcap-ffxiv**. Therefore opcodes can be tested before published by putting the files in `%tc-root%/app-%version%/resources/localOpcodes`.
=> feat(packet-capture): allow loading local opcodes for testing

apps/client/src/app/modules/tooltip/xivapi-action-tooltip/xivapi-action-tooltip.directive.ts
Currently, drag and drop can cause the mouseleave event to be missing if the action element moves. This leaks the tooltip overlay element when mousing over the action again. Prevent this by checking for an existing OverlayRef when creating a tooltip.
=> fix(simulator): Prevent tooltip leak

apps/client/src/assets/opensearch.xml
The XML had an error when adding to Firefox. 
With this change the search engine can be added. Tested on Firefox 88.0.1
=> Correction of a XML Error

apps/electron/src/pcap/packet-capture.ts
Move the powershell exec to a synchronous one with a timeout.
Resolve issue where the exec call never stop and never trigger the callback.
As the call to powershell to check the pcap service may never finish, the callback to start Machina is also never triggered.
To fix that, the shell call is now synchronous, has a timeout and stdio parameters to make more robust.
=> fix(pcap): force powershell to stop

apps/client/src/app/pages/log-tracker/fishing-log-tracker/fishing-log-tracker.component.html
The GatheringNode model calls the hooksets `precision` and `powerful` but the template is checking for `Precision Hookset` so the tooltip ends up always displaying Powerful Hookset. I saw there's an enum for normal/precision/powerful so ideally we should have the model use that with action IDs as a value or some sort of simple function to get an ID, but this fix is a quick and dirty one that matches the model.
=> fix(log-tracker): use correct hookset string for tooltip

apps/client/src/app/pages/db/fishing-spot/fishing-spot-bite-times/fishing-spot-bite-times.component.ts
* Updates the whisker box tooltips to use the whisker min/max values instead of the outlier min/max
* Adds the display of outliers
* Removes the color indicator from tooltips
* Moves the s(econds) unit from the axis ticks to the axis label.
It is now possible to internationalize the bite time tooltips if desired.
I also recommend considering the addition of a toggle to the bite times table for the display of outlier data.
=> refactor(db): improve display of fish bite times

apps/client/src/app/+state/auth.facade.ts, apps/client/src/app/core/electron/ipc.service.ts, apps/client/src/app/modules/marketboard/marketboard-popup/marketboard-popup.component.ts
This PR fixes two things which contributed to marketboard popup, even after being closed, causing additional requests to Universalis, sometimes in great numbers.
1. Unnecessary (new value === old value) world ID updates, which caused execution of all downstream functions, including re-retrieving data from Universalis even though nothing has changed.
2. Observables in marketboard popup component surviving the destruction of the popup window itself, which caused them to request updates to marketboard data without any benefit to the user.
This PR couldn't have happened without ample help from Miu and Ay, thanks!
=> Fix excessive universalis requests in marketboard popup

apps/client/src/app/modules/free-company-workshops/+state/free-company-workshop.facade.ts
This only affects those regions with patch 6.3. ZH/KR are not affected by this.
=> Update Submarine max level to 105.

apps/client/src/assets/i18n/en.json
Since this does come up quite often as a question in the discord, the failure message has been reworded to better express both the expected time it takes Lodestone cache to update, and that it is not needed for almost all features of TC.
=> chore(verification): change error message

apps/client/src/app/pages/island-workshop/island-workshop/island-workshop.component.html, apps/client/src/app/pages/island-workshop/island-workshop/island-workshop.component.ts, apps/client/src/app/pages/island-workshop/workshop-planning/workshop-planning.component.html, apps/client/src/app/pages/island-workshop/workshop-planning/workshop-planning.component.ts, apps/client/src/assets/i18n/en.json, apps/client/src/assets/i18n/ja-JP.json, apps/client/src/assets/i18n/zh-CN.json
updated workshop planning to display item category and craft time
* added a toggle for this feature (defaults to true)
* added translations for CN and JP
=> feat(island-workshop): new checkbox to display item metadata in planning

apps/client/src/app/pages/island-workshop/optimizer/planning-formula-optimizer.ts
With C2 patterns, C2 items will often not be distinguishable between strong or weak, so isPeaking can be true when it has 2 patterns.
Other cycles can have 2 patterns, but they would not have the right dayIndex so this will not errantly set isPeaking.
=> fix(island-workshop): allowed items with undetermined C2 peak type to be considered for best item to use

apps/client/src/app/core/electron/ipc.service.ts
The line was recently changed from 60000 ms (60 seconds) to 1200000 ms (1200 seconds), instead of the intended 120000 ms (120 seconds). Also, updated the comment :)
=> Fixed extra '0' in debounceTime call

apps/client/src/app/pages/voyage-tracker/voyage-tracker.module.ts, apps/client/src/app/pages/voyage-tracker/voyage-tracker/vessel-row/vessel-build-column/vessel-build-column.component.html, apps/client/src/app/pages/voyage-tracker/voyage-tracker/vessel-row/vessel-build-column/vessel-build-column.component.less, apps/client/src/app/pages/voyage-tracker/voyage-tracker/vessel-row/vessel-build-column/vessel-build-column.component.ts, apps/client/src/app/pages/voyage-tracker/voyage-tracker/vessel-row/vessel-rank-column/vessel-rank-column.component.html, apps/client/src/app/pages/voyage-tracker/voyage-tracker/vessel-row/vessel-rank-column/vessel-rank-column.component.ts, apps/client/src/app/pages/voyage-tracker/voyage-tracker/vessel-row/vessel-row.component.html, apps/client/src/assets/i18n/en.json
This is two small changes to show a little more info in the voyage tracker.
1) The abbreviated build in the build column is now colored to give an indication of the worst condition on the parts so it's easier to tell when a vehicle needs to be repaired without having to mouse over the build and look at the popup. It would be possible to instead color each part letter separately but that was more effort, would perhaps be enough extra color to be distracting, and it's generally sufficient to know the worst part condition because parts with higher than 0 don't need to be repaired anyway. Still, I'm not thrilled with how this looks and maybe it would be better to have a vertical red/green bar kind of icon like we see in game shown next to the build abbreviation.
2) Added a popover to the …
=> feat/voyage tracker UI enhancements

apps/client/src/app/pages/voyage-tracker/voyage-tracker/vessel-row/vessel-rank-column/vessel-rank-column.component.html
XP progress popover is disabled though since max rank vehicles are unable to earn any XP.
=> fix(voyage-tracker): display rank when at max rank

apps/client/src/app/core/layout/layout.service.ts
Removing a blank space to allow keyword translation on Vendors list layout
=> fix(translation): remove blank space to allow word translation

apps/client/src/app/core/alarms/+state/alarms.facade.ts, apps/client/src/app/modules/custom-alarm-popup/custom-alarm-popup/custom-alarm-popup.component.ts, apps/client/src/app/pages/alarms-page/alarms-page/alarms-page.component.html
Adding a default value for weather on custom alarm form Allow alarm with missing spawns and remaining time to be displayed
=> fix(custom-alarm-without-weather): custom alarm without weather are now properly displayed

apps/client/src/app/core/alarms/realtime-alarms.service.ts, apps/client/src/assets/i18n/de-DE.json, apps/client/src/assets/i18n/en.json, apps/client/src/assets/i18n/es-ES.json, apps/client/src/assets/i18n/fr-FR.json, apps/client/src/assets/i18n/hr-HR.json, apps/client/src/assets/i18n/ja-JP.json, apps/client/src/assets/i18n/ko-KR.json, apps/client/src/assets/i18n/nl-NL.json, apps/client/src/assets/i18n/pt-BR.json, apps/client/src/assets/i18n/pt-PT.json, apps/client/src/assets/i18n/ru-RU.json, apps/client/src/assets/i18n/zh-CN.json
You can now enable a reminder for ocean fishing on reminders page
=> feat(add-reminder-for-ocean-fishing): add a new reminder for ocean fishing every two hours

apps/client/src/assets/i18n/en.json
Removes an unnecessary comma in the English language file.
While removing translation keys, an extra comma was left in, so now it's invalid JSON.
Firefox no longer shows the English UI with the staging branch.
* Introduced in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/927a7d65e74d8ced66fe703b82dc3c9b5138872f#diff-def7e78050b579a674ce4e511d200b764375bfe975ce8bcb03568b85607d8c22L1267
=> fix(i18n): en language file

CONTRIBUTING.md
Minor PR that just makes the formatting of CONTRIBUTING.md more consistent. Welcome to dispute the changes.
* Titles should be either sentence case, or title case. But mix and matching is a bit uncomfortable. ^-^'
* Windows and GitHub are both proper nouns, so casing matters! i.e. Github → GitHub
* Not sure why, but each line in **Commit Message** was prefixed with a whitespace.
* Fixes link anchor to **Important Note: Fishing Data and Allagan Reports**.
=> docs: fix inconsistent formatting in contributing guide

apps/client/src/app/app.component.ts, apps/client/src/index.html
This PR sets `html[lang]` with the current language, and updates it if the language is changed while in the SPA.
On the web it helps browsers, translation tools, and screen readers if the language of the content is defined in `html[lang]`.
For example:
* Translation tools know what to translate the page from without user input.
* Screen readers know what language/accent to use when reading content.
> This Success Criterion helps:
>
> * people who use screen readers or other technologies that convert text into synthetic speech;
> * people who find it difficult to read written material with fluency and accuracy, such as recognizing characters and alphabets or decoding words;
> * people with certain cognitive, language and learning disabilities who use text-to-speech software
> * people who …
=> fix(accessibility): add lang attribute to html

apps/client/src/app/modules/item-details/trades/trades.component.html, apps/client/src/app/modules/list/item/item-sources-display/item-sources-display.component.ts, apps/client/src/assets/i18n/de-DE.json, apps/client/src/assets/i18n/es-ES.json, apps/client/src/assets/i18n/fr-FR.json, apps/client/src/assets/i18n/hr-HR.json, apps/client/src/assets/i18n/ja-JP.json, apps/client/src/assets/i18n/ko-KR.json, apps/client/src/assets/i18n/nl-NL.json, apps/client/src/assets/i18n/pt-BR.json, apps/client/src/assets/i18n/pt-PT.json, apps/client/src/assets/i18n/ru-RU.json, apps/client/src/assets/i18n/zh-CN.json, libs/data/src/lib/lazy-files-list.ts
* **desktop:** new option in tray menu to toggle always on top.
* **inventory-optimizer:** new "items not used in any of your lists" optimizer.
* **tooltips:** added rlvl and quality to recipe details.
* **core:** hide desktop tip banner on mobile.
* **db:** fixed items showing wrong value for Class/job.
* **db:** fixed progress value not shown on recipe details.
* **ios:** possible fix for older ios browsers.
* **list:** monster icon is now larger.
* **lists:** fixed "mark panel content as done" on offline lists.
* **simulator:** fixed a bug preventing custom rotations from saving.
* **simulator:** fixed rotation finder not loading and poor simulator perfs.
* **tooltips:** added 500ms delay before closing and they now stay opened on mouseover.
=> 11.0.3 with a trades popup hotfix

apps/client/src/app/core/push-notifications.service.ts
Accessing `!!Notification` is failing on iOS. Using the official check `'Notification' in window` fixed the issue. I tested it with iOS Safari, iPad Safari and Chrome on Windows.
Alerting will not work as this will return `false` on the check. iOS Safari is supporting the Notification API since 16.4, so it SHOULD be possible to get it working with the limitation of having to add the site to the home screen first. But I think this is for another PR :) My highest prio was getting the site to load again.
The firebase errors were false flags and the only real problem was the notification check crashing the whole app after all.
=> fix(ios): fix notification check on iOS

apps/client/src/app/pages/collectables/collectables/collectables.component.html, apps/client/src/app/pages/db/item/item.component.html, apps/data-extraction/src/extractors/collectables.extractor.ts, apps/data-extraction/src/extractors/extracts/trade-sources.extractor.ts, libs/data/src/lib/json/collectables.json
Fixes:
- Quantity was wrong, it seems to always be 1 -> N and not N -> N.
- minCollectability was taken from the base quality instead of the appropriate quality.
- Trades of items like 31101/Oddly-Specific-Cedar-Lumber properly reward 30315/Carpenter's-Gobbiegoo instead of Skybuilder's Scrips.
- Handles missing "high" quality for items such as 38763/Connoisseur's-Pixieberry-Tea in the presentation layer.
- Removes special handling for CollectablesShopItem and those are all covered (and overriden) by CollectablesShop & CollectablesShopRewardItem.
=> fix(data-extraction): Fix collectable rating, quantities and rewards

apps/client/src/app/pages/simulator/rotation-tips/tips/use-durability-restoration-later.ts
See issue https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/2686, bug: use-durability-restoration-later tip does not adjust index for filtered steps
=> fix(simulator): Fix logic for manipulation check in use-durability-restoration-later tip

apps/client/src/app/pages/log-tracker/log-tracker/log-tracker.component.html, apps/client/src/app/pages/log-tracker/log-tracker/log-tracker.component.ts
Fixes #2061 partially. I noticed 2 scenarios where it still happens : 
- Switching back and forth between 2 DoH jobs. The current page index of a job gets stored somehow, and it mess up the page display when switching back and forth with another job. I suspect it is an issue with the html template, as it doesn't happen with DoL sub tabs, but I can't pinpoint the exact spot.
- Somewhat randomly when switching between DoH and DoL. I think it's a lazy loading/race condition issue, but didn't investigate very far.
=> fix(log-tracker): Ensure correct page is displayed when 'Hide Completed' is enabled.

apps/client/src/app/core/layout/layout-row-filter.ts
I added this filter because the solution in #2479 doesn't work properly, since some items can be bought from tribe vendors as well as normal vendors.
CAN_BE_BOUGHT AND NOT FROM_BEAST_TRIBE:
CAN_BE_BOUGHT_WITHOUT_TRIBES:
=> feat(layouts): Add CAN_BE_BOUGHT_WITHOUT_TRIBES layout filter

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json
Updates the .vscode/ config files to support out-of-the-box debugging with breakpoints. After following the prerequisite steps outlined in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/CONTRIBUTING.md, users can run the "Launch edge" configuration which will serve a debuggable application and open an edge browser
Emphasis on "with breakpoints". I'm sure this is trivial to people who are familiar with TS and Angular, but as someone who has never worked with it, getting to this point took more time than I'd like to admit. I'm hoping having these settings in the repo will lower the entry barrier to others looking to contribute.
=> chore(Debugging): Add vscode config settings for debugging

.vscode/launch.json, .vscode/tasks.json
If you focus off the console window (by navigating to another one) that the preLaunchTask launches and then end the debugging session, the console window does not close
This PR adds a postDebugTask (essentially the opposite of "preLaunchTask") that ensures the preLaunchTask console window is closed
=> Ensure termination of preLaunchTask in "Launch Edge" vscode config

.vscode/launch.json, .vscode/tasks.json
Defines a VSCode configuration for launching a Teamcraft desktop app. The configuration follows the steps outlined in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/CONTRIBUTING.md#the-desktop-app
The configuration starts the `build:watch` package.json script in a dedicated terminal. Once that has finished building and starts watching for file changes, the `electron:start` package.json script is ran and launches the Teamcraft app. The `build:watch` script continues to run until the configuration is terminated (ie user closes Teamcraft app or explicitly stops the debugging session)
For changes that are picked up by the --watch flag and trigger new dist files to be generated, simply refreshing the app via CTRL-R will reflect the changes in the app and an entire re-run of …
=> chore(Debugging): VSCode Configuration for Main electron process

package.json
Update the version of electon-build to stop generating Debug versions. This generates a Release version of dll-inject which doesn't trigger the AV programs.
electron-userland/electron-builder#8531
=> fix(desktop): Correct build of dll-inject to avoid AV issue
