ffxiv-teamcraft/ffxiv-teamcraft

- src/app/core/data.service.ts
> feat: point recipe links directly to the item page

- src/app/pricing/pricing-row/pricing-row.component.html
- src/app/pricing/pricing-row/pricing-row.component.scss
- src/app/pricing/pricing-row/pricing-row.component.ts
- src/app/pricing/pricing.module.ts
- src/app/pricing/pricing.service.ts
- src/app/pricing/pricing/pricing.component.html
- src/app/pricing/pricing/pricing.component.ts
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/ja.json
> feat: see price for a given craft in pricing view

- src/app/app.module.ts
- src/app/component/item/item.component.html
- src/app/component/item/item.component.ts
- src/app/component/list-details-panel/list-details-panel.component.html
- src/app/component/list-details-panel/list-details-panel.component.ts
- src/app/component/list-details/list-details.component.html
- src/app/component/popup/required-by-popup/required-by-popup.component.html
- src/app/component/popup/required-by-popup/required-by-popup.component.ts
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/ja.json
> feat: add informations about which recipe needs a given ingredient

- src/app/app.module.ts
- src/app/component/cart-import/cart-import.component.html
- src/app/component/cart-import/cart-import.component.scss
- src/app/component/cart-import/cart-import.component.ts
- src/app/component/common/random-gif/random-gif.component.html
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/ja.json
> feat: add support for xivdb cart imports

- src/app/modules/item/item/item.component.ts
Update of all trade currencies as of 4.1
> chore: update trade sources

- src/app/modules/item/item/item.component.ts
Raid currencies, primals totems, hunt log, rowena's token, world boss
> feat: addition of currencies for non-craftable gear

- src/app/pages/lists/lists.module.ts
- src/app/pages/lists/lists/lists.component.html
- src/app/pages/lists/lists/lists.component.scss
- src/app/pages/lists/lists/lists.component.ts
- src/app/pages/lists/merge-lists-popup/merge-lists-popup.component.html
- src/app/pages/lists/merge-lists-popup/merge-lists-popup.component.ts
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/ja.json
> feat: add list merging

- src/app/core/list/data/data-extractor.service.ts
- src/app/modules/item/vendors-details-popup/vendors-details-popup.component.html
- src/app/modules/pricing/pricing-row/pricing-row.component.html
- src/app/modules/pricing/pricing.service.ts
- src/app/modules/pricing/pricing/pricing.component.html
- src/assets/i18n/en.json
- src/assets/i18n/ja.json
The plural form of 'gil' is 'gil'
> Style: Correct currency name display.

- src/app/model/list/list-tag.enum.ts
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/ja.json
> feat: add QUEST tag for public lists

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.component.html
- src/app/core/core.module.ts
- src/app/core/data/bell-nodes.service.ts
- src/app/core/data/language.ts
- src/app/core/data/localized-data.service.ts
- src/app/core/time/alarm.service.ts
- src/app/modules/common-components/list-panel/list-panel.component.html
- src/app/modules/common-components/list-panel/list-panel.component.scss
- src/app/modules/common-components/list-panel/list-panel.component.ts
- src/app/modules/item/gathered-by-popup/gathered-by-popup.component.html
- src/app/modules/item/gathered-by-popup/gathered-by-popup.component.ts
- src/app/pages/alarms/add-alarm-popup/add-alarm-popup.component.html
- src/app/pages/alarms/add-alarm-popup/add-alarm-popup.component.scss
- src/app/pages/alarms/add-alarm-popup/add-alarm-popup.component.ts
- src/app/pages/alarms/alarm-card/alarm-card.component.html
- src/app/pages/alarms/alarms.module.ts
- src/app/pages/alarms/alarms/alarms.component.html
- src/app/pages/alarms/alarms/alarms.component.scss
- src/app/pages/alarms/alarms/alarms.component.ts
- src/app/pages/list/list-details/list-details.component.ts
- src/app/pages/lists/lists/lists.component.html
- src/app/pages/lists/lists/lists.component.scss
- src/app/pages/public-lists/public-lists/public-lists.component.html
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/ja.json
> feat: add possibility to create node alarms without any list

- .github/ISSUE_TEMPLATE.md
* note for bug and feature tag
* shorter environment form (didn't cover every possible browser anyway)
* note on script/adblockers
* feature request separation
> chore: shorter issue_template

- .github/ISSUE_TEMPLATE.md
checkboxes look nice, but they introduce a progress-bar in the issue listing, not very helpful in this case
> chore: remove checkbox from issue_template

- .github/ISSUE_TEMPLATE.md
last change still resulted in checkboxes, so we're taking the sledgehammer approach.
> chore: issue_template checkbox fix - take 2

- src/app/modules/item/item/item.component.ts
Added 4.3 currencies (Tsukuyomi, Namazu, Ridorana)
> chore: added 4.3 currencies

- src/app/pages/list/list/list.component.html
Fixes #412 by relocating the error message to where it will be properly displayed
> fix: no message on list not found

- main.js
- src/app/core/electron/ipc.service.ts
- src/app/pages/settings/settings.module.ts
- src/app/pages/settings/settings/settings.component.html
- src/app/pages/settings/settings/settings.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
> feat(desktop): new toggle button in settings to always have Teamcraft on top

- src/assets/i18n/de.json
Translating mostly everything
* still needs some better words
* needs some context on some items
> [WIP] chore: Add German translation for commission board

- src/assets/wiki/en/commission_request
> docs: added wiki page for creating a commission

- src/assets/wiki/en/Select_Commisson
> docs: added wiki page for selecting a commission

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/pages/about/about.module.ts
- src/app/pages/add-item/add-item.module.ts
- src/app/pages/alarms/alarms.module.ts
- src/app/pages/custom-links/custom-links.module.ts
- src/app/pages/gathering-location/gathering-location.module.ts
- src/app/pages/home/home.module.ts
- src/app/pages/link/link.module.ts
- src/app/pages/lists/lists.module.ts
- src/app/pages/macro-translation/macro-translation.module.ts
- src/app/pages/profile/profile.module.ts
- src/app/pages/public-lists/public-lists.module.ts
- src/app/pages/recipes/recipes.module.ts
> refactor: routing now done with lazy loading for better performances and less network usage

- .gitignore
- src/app/pages/simulator/components/custom-simulator-page/custom-simulator-page.component.html
- src/app/pages/simulator/components/custom-simulator-page/custom-simulator-page.component.scss
- src/app/pages/simulator/components/custom-simulator-page/custom-simulator-page.component.ts
Allows users to select a base recipe for a custom rotation which updates
the recipe configuration accordingly. Also adds some spacing to the
form and a couple new files to ignore.
> feat: recipe selection for custom rotations

- src/app/pages/gathering-location/gathering-location/gathering-location.component.ts
> fix: fixed an issue preventing gathering location page to create alarms

- src/app/pages/commission-board/commission-board.module.ts
- src/app/pages/commission-board/commission-details/commission-details.component.html
- src/app/pages/commission-board/commission-details/commission-details.component.scss
- src/app/pages/commission-board/commission-details/commission-details.component.ts
- src/app/pages/commission-board/rating/rating.component.html
- src/app/pages/commission-board/rating/rating.component.scss
- src/app/pages/commission-board/rating/rating.component.ts
- src/app/pages/profile/profile.module.ts
- src/app/pages/profile/profile/profile.component.html
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/assets/i18n/fr.json
- src/assets/i18n/pt.json
Refactors the rating into a reusable component and includes it on the user's profile page. Minor style changes. Resolves #482
>  feat: rating shown on profile

- src/assets/i18n/es.json
Spanish localization was not loading due to an error in the JSON file.
Added the missing `}` and fixed up the formatting near the EOF.
> fix: spanish localization

- src/app/model/list/list-row.ts
- src/app/model/list/list.ts
- src/app/modules/item/item.module.ts
- src/app/modules/item/item/item.component.html
- src/app/modules/item/item/item.component.scss
- src/app/modules/item/item/item.component.ts
Adds dashed blue border to end items that have all final ingredients completed to be created.
Example:
- I create a list for Twinsilk
- It requires Twinthreads
- I check all the twincocoons (required for threads) and the water.
- TwinThreads row become blue
- Twinsilk row gets the dashed border because I only have crafts to do to get the item now.
> feat: priority items

- package-lock.json
- package.json
- src/app/pages/simulator/components/action/action.component.scss
- src/app/pages/simulator/components/rotations-page/rotations-page.component.html
- src/app/pages/simulator/components/rotations-page/rotations-page.component.scss
- src/app/pages/simulator/components/simulator/simulator.component.html
- src/app/pages/simulator/components/simulator/simulator.component.scss
> fix: fixed some drag and drop issues, including timeline jitter in simulator

- src/assets/i18n/de.json
Reordered translations to fit the English file and added missing translations, also fixed some minor things with in my opinion better translations
> Added missing translations

- src/app/pages/list/list-details/list-details.component.html
- src/app/pages/recipes/recipes/recipes.component.html
- src/app/pages/recipes/recipes/recipes.component.ts
Verifies that the user is authenticated (not anonymous) before displaying the commission creation buttons.
Fixes #533
> fix: anonymous commissions

- src/app/pages/commission-board/server-history/server-history.component.html
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
Provides a proper message for servers with no commission history.
> fix: no server history message

- src/app/pages/simulator/components/simulator/simulator.component.scss
Removes hanging threshold marker and widens a bit for easier mouseover.
> refactor: quality threshold styling

- src/index.html
Adds a description tag for Google search results and tweaks the existing wording. Fixes title consistency.
> refactor: meta tags

- apps/client/src/app/app.component.html
- apps/client/src/app/app.component.less
- apps/client/src/app/modules/settings/settings-popup/settings-popup.component.html
- apps/client/src/app/modules/settings/settings.service.ts
- apps/client/src/assets/i18n/en.json
Removes bright borders in various places, reduces contrast
Mainly useful for `/lists` and list details
> feat: Add option to remove panel borders

- apps/client/src/app/core/api/data.service.ts
I mistake to write commit message include support Chinese.
> feat(localisation): you can now search in Korean and Chinese from Gathering items

- apps/client/src/app/pages/recipe-finder/recipe-finder/recipe-finder.component.html
- apps/client/src/app/pages/recipe-finder/recipe-finder/recipe-finder.component.ts
Fixes an issue where the recipe finder was being passed incorrect values causing fewer than expected pages to show up.
Adds some extra features to the pagination for easier navigation.
> fix: Recipe Finder Pagination

- apps/client/src/app/pages/lists/list-import-popup/link-parser/ariyala-link-parser.ts
- apps/client/src/app/pages/lists/list-import-popup/link-parser/ariyala-materia-options.ts
- apps/client/src/app/pages/lists/list-import-popup/list-import-popup.component.html
- apps/client/src/app/pages/lists/list-import-popup/list-import-popup.component.ts
- apps/client/src/assets/i18n/en.json
Originally I created this script and posted it in the balance discord:
https://pastebin.com/mBN967ns
Pasted to developer console, it allows you to see how much materias you will need for overmelding, based on the overmeld chances.
Now I implemented it within the Ariyala link importer as suggested by @Supamiu 😊
Please note I have never programmed in Typescript, Angular or RxJS before, so change in order to accommodate your own conventions if necessary.
New translations will also need to be added.
> Feature for materia amount estimation

- apps/client/src/app/pages/list-details/list-details/list-details.component.ts
Changes for my issue ffxiv-teamcraft#1071.
Add some codes for row.done not correctly.
Please review again, thx.
> feat: amount of list text export not consider the done amount

- apps/client/src/app/pages/simulator/rotation-tips/tips/use-durability-restoration-later.ts
Changes durability value to 30 from 60
> fix(simulator): Correct trigger of durability restoration tip

- apps/client/src/app/pages/simulator/components/macro-popup/macro-popup.component.html
- apps/client/src/app/pages/simulator/components/macro-popup/macro-popup.component.ts
No more reclaim, no more breakpoint
> chore(simulator): Remove break on reclaim

- apps/client/src/app/pages/simulator/rotation-tips/tips/do-not-use-brand-without-name.ts
Seems I forgot some parentheses
> fix(simulator): fix brand of elements tip incorrectly triggering

- apps/client/src/app/modules/settings/settings.service.ts
- apps/client/src/app/pages/simulator/components/macro-popup/macro-popup.component.ts
Also switched to using the SettingsService instead of directly into localStorage
> feat(simulator): Remember all options in macro creator

- package-lock.json
- package.json
Update node-machina-ffxiv to 2.22.2
> fix: retarget .NET version to restore packet capture on Windows 8.

- apps/client/src/assets/i18n/de-DE.json
- apps/client/src/assets/i18n/en.json
- apps/client/src/assets/i18n/es-ES.json
- apps/client/src/assets/i18n/fr-FR.json
- apps/client/src/assets/i18n/hr-HR.json
- apps/client/src/assets/i18n/ja-JP.json
- apps/client/src/assets/i18n/ko-KR.json
- apps/client/src/assets/i18n/pt-BR.json
- apps/client/src/assets/i18n/pt-PT.json
- apps/client/src/assets/i18n/ru-RU.json
- apps/client/src/assets/i18n/zh-CN.json
there were spelling errors in the message properties for Ignore_container and Remove_ignore_container.
Fixed for all langauge json files
> Fix ignore_container language properties

- apps/client/src/app/pages/db/fish/fish.component.ts
> chore: fix for display on fishes with no data

- apps/client/src/app/core/data-reporting/fishing-reporter.ts
> chore: avoid reporting data that isn't possible

- package.json
> chore: change artifact name for nsis web target

- package-lock.json
- package.json
https://github.com/karashiiro/MachinaWrapperJSON/pull/13
https://github.com/karashiiro/MachinaWrapperJSON/commit/2007bc99f1cc94e49eb31de9897e601d35c4dfbd
> chore: Update node-machina-ffxiv to 2.30.4

- apps/client/src/app/core/layout/layout-order.service.ts
- apps/client/src/app/modules/list/list-details-panel/list-details-panel.component.ts
> fix(list): hotfix for list details not loading properly

- apps/client/src/assets/i18n/en.json
Make password confirmation more clear to the user by changing the inputs label from "Confirmation: " to "Confirm Password: "
> Chore: Password Confirmation Clarification

- apps/client/src/app/pages/list-details/list-details/list-details.component.ts
> fix(list): fixed "add all alarms for this list" button

- apps/client/src/assets/i18n/ko-KR.json
previous: star = 20% more exp
after: star = 20% more reward
> better translation for KR

- apps/client/src/app/modules/list/item/item-row-buttons/item-row-buttons.component.html
> chore: hotfix for new list buttons component

- apps/client/src/app/core/database/storage/firestore/firestore-relational-storage.ts
- apps/client/src/app/core/database/storage/list/firestore-list-storage.ts
- apps/client/src/app/modules/list/+state/lists.actions.ts
- apps/client/src/app/modules/list/+state/lists.effects.ts
- apps/client/src/app/modules/list/+state/lists.facade.ts
- apps/client/src/app/modules/list/+state/lists.reducer.ts
- apps/client/src/app/modules/list/list-completion-popup/list-completion-popup.component.html
- apps/client/src/app/modules/list/list-completion-popup/list-completion-popup.component.ts
- apps/client/src/app/modules/list/list-panel/list-panel.component.html
- apps/client/src/app/pages/list-details/list-details/list-details.component.html
- apps/client/src/app/pages/list-details/list-details/list-details.component.ts
- apps/client/src/app/pages/lists/lists/lists.component.html
- apps/client/src/app/pages/lists/lists/lists.component.ts
- apps/client/src/assets/i18n/en.json
> feat(lists): you can now archive lists, which makes them not load by default

- apps/client/src/app/core/data/lazy-data.service.ts
- apps/client/src/app/core/data/lazy-data.ts
my fault, the calculation is fixed
> feat(db): added recipes for chinese version and fixed wrong HQ ingredients quality

- apps/client/src/app/pages/gearset/gearset-editor/gearset-editor.component.html
- apps/client/src/assets/i18n/en.json
Changes:
* Gearset editor: Fix alignment of footer fields
The class and level input widgets in the Gearset Editor footer were
misaligned.
* en.json entry for GEARSETS.Total_cost
> Gearset editor fixes

- apps/client/src/app/modules/settings/settings-popup/settings-popup.component.html
- apps/client/src/app/modules/settings/settings.service.ts
- apps/client/src/app/pages/levequests/levequests/levequests.component.ts
- apps/client/src/assets/i18n/en.json
> feat(ux): setting for always doing large leves

- apps/client/src/app/pages/list-details/total-panel-price-popup/total-panel-price-popup.component.ts
Fixes #1426 
I admit I haven't tried to ignore currencies like this before, so my testing was limited to matching the screenshot provided in the issue, as well as me trying some lists with Scaevan gear. It worked fine for those, but I'm unsure if this will break something else.
> fix(lists): fix ignore currencies in total trades

- apps/client/src/app/core/electron/machina.service.ts
Ok, It's really fixed.
I also learned how to build the app. It very works. 😄
> fix(desktop): fixed retainer tracking KR/CN

- apps/client/src/app/core/eorzea/timer.pipe.ts
https://discordapp.com/channels/355013337748209665/639503745176174592/684561814800957461
> fix(alarms): Display hours when zero on timers and alarms longer than a day

- apps/client/src/app/modules/pricing/pricing/pricing.component.ts
> feat(pricing): Add server name to text export

- apps/client/src/index.html
> feat: patreon new goddess of the hand

- apps/client/src/app/app.component.html
- apps/client/src/app/modules/settings/settings-popup/settings-popup.component.html
- apps/client/src/app/modules/settings/settings-popup/settings-popup.component.less
- apps/client/src/app/modules/settings/settings-popup/settings-popup.component.ts
- apps/client/src/assets/i18n/en.json
- desktop/main.js
> feat: user-friendly proxy setting

- apps/client/src/app/core/auth/character-link-popup/character-link-popup.component.ts
Added 3 new chinese servers and sort as official order.
Official chinese servers list: http://ff.sdo.com/web8/index.html#/servers
> chore: add new chinese servers

- apps/client/src/app/core/api/data.service.ts
Also, It fixed the problem showing all items when there is no Korean search result
> feat(search): search in English if search in Korean has no results

- desktop/main.js
Just moved two snippets around and it seems to have fixed the following error about machina being undefined. I built TC installed the app and got no error on launch as well as when I pushed the button in settings it added the firewall rule and packet capture started working proper.
> Bug: Machina firewall error

- package.json
- yarn.lock
uhhh,, I lost `c` in commit message.
> fix(desktop): fix inventory tracking for KR

- apps/client/src/app/app-routing.module.ts
- apps/client/src/app/app.component.html
- apps/client/src/app/pages/food-picker/food-picker.module.ts
- apps/client/src/app/pages/food-picker/food-picker/food-picker.component.html
- apps/client/src/app/pages/food-picker/food-picker/food-picker.component.less
- apps/client/src/app/pages/food-picker/food-picker/food-picker.component.ts
- apps/client/src/app/pages/food-picker/food-picker/stat-entry.ts
- apps/client/src/assets/i18n/en.json
- apps/client/src/environments/patch-notes.ts
PR to answer issue #1639 
Provides basic functionality to choose from up to 3 attributes, and display back the foods providing those attributes along with their bonuses values.
1st iteration here, I'm planning to improve this feature later by adding medicines along with food results, and improve the overall visuals.
And thank you again Miu for helping me for this feature :)
> Feat: Food Picker Helper

- apps/client/src/app/modules/workshop/+state/workshops.facade.ts
> fix(workshops): fixed duplicate workshops with some specific sharing conditions

- apps/client/src/app/modules/player-metrics/player-metrics.service.ts
closes #1622
Might also fix #1621 but I'm not sure yet.
> fix(metrics): fixed an issue with single day data loading

- apps/client/src/app/modules/settings/settings.service.ts
- apps/client/src/app/pages/simulator/components/simulator/simulator.component.html
- apps/client/src/app/pages/simulator/components/simulator/simulator.component.less
- apps/client/src/assets/i18n/en.json
> feat(simulator): new detailed display option for actions list

- apps/client/src/app/pages/simulator/components/rotation-folder-panel/rotation-folder-panel.component.html
> chore: added favorite button to rotation folders

- CONTRIBUTING.md
- apps/client/src/app/pages/support-us/support-us/support-us.component.html
- apps/client/src/assets/wiki/en/contributing.md
- apps/client/src/assets/wiki/en/home.md
- apps/client/src/assets/wiki/en/list-details.md
- apps/client/src/assets/wiki/en/simulator.md
Updated urls to use ffxiv-teamcraft/ffxiv-teamcraft
> docs: Update repository url

- apps/client/src/app/core/electron/ipc.service.ts
- apps/client/src/app/modules/free-company-workshops/free-company-workshops.module.ts
- apps/client/src/app/modules/free-company-workshops/import-workshop-from-pcap-popup/import-workshop-from-pcap-popup.component.ts
- apps/client/src/app/pages/voyage-tracker/voyage-tracker/voyage-tracker.component.html
- apps/client/src/app/pages/voyage-tracker/voyage-tracker/voyage-tracker.component.ts
- apps/client/src/assets/i18n/en.json
- should work for KR/CN (would be nice to have someone from KR/CN to actually confirm it)
- fix the discovered airship sectors count where Diadem wasn't removed from the count
> Voyage tracker kr cn support

- apps/client/src/app/core/data-reporting/airship-exploration-result-reporter.ts
- apps/client/src/app/core/data-reporting/exploration-result.reporter.ts
- apps/client/src/app/core/data-reporting/submarine-exploration-result-reporter.ts
@shambarick You'll want to check this one 🙂
> refactor(submarine-reporter): better observable chain for the reporter and unicity for reports

- apps/client/src/app/core/alarms/+state/alarms.facade.ts
- apps/client/src/app/modules/node-details/node-details/node-details.component.ts
Fixes dark matter node alarms to not group up on the same zone making so all current 37 alarms being able to be registered instead of 21
> fix(Alarms): fix nodes to not group if on same zone

- apps/client/src/app/modules/free-company-workshops/import-workshop-from-pcap-popup/import-workshop-from-pcap-popup.component.ts
- apps/electron/src/pcap/packet-capture.ts
The issue is totally on me for forgetting to commit the latest changes when I pushed last time.
Tho, the only thing left is the uppercase on the first letter of the server name. I'm not sure how to deal with that because of CN/KR and I didn't find any snippets that map an `ID` to the `Server Name`.
Eg: Jenova(expected) vs jenova(currently with this PR)
> fix(voyage-tracker): fix import

- apps/client/src/assets/data/ko/ko-action-descriptions.json
- apps/client/src/environments/game-env.ts
It's not important db update, but opcodes are changed.
> chore: korean v5.551 hotfix update

- apps/client/src/app/pages/allagan-reports/model/allagan-report-source.ts
- apps/client/src/app/pages/allagan-reports/report-source-compact-details/report-source-compact-details.component.html
- apps/client/src/app/pages/allagan-reports/report-source-display/report-source-display.component.html
- apps/client/src/assets/i18n/en.json
Changed all instances (hopefully) of DESYNTH source to DESYNTHED_FROM to reduce confusion when submitting Allagan Reports.
Changed Allagan Reports button label to "Add or modify data sources for this item" to make it known to user that they may modify existing reports.
Assorted minor proofreading/clarity tweaks to en.json.
> Change DESYNTH to DESYNTHED_FROM in Allagan Reports + proofreading

- CONTRIBUTING.md
Update the contributor's documentation to include instructions for
developing on Windows and adjust the supported node version to reflect
up stream dependecies.
Closes #2211
> docs: update environment instructions

- apps/client/src/environments/game-env.ts
- package.json
- yarn.lock
Ceebs micromanaging every commit message so lets see if PR title works. I figure Miu has this already in progress but some peeps were asking about the sim specifically and this really just sets the game ver and sim ver anyway.
> chore(simulator): Bump support for CN 6.0

- CONTRIBUTING.md
docs(contributing): added getting started section
> docs(contributing): added getting started section

- apps/client/src/app/core/data-reporting/data-reporters-index.ts
> chore: don't forget to keep the reporter enabled !

- apps/client/src/app/core/alarms/+state/alarms.facade.ts
- apps/client/src/app/core/alarms/alarm-bell.service.ts
> chore: alarm hotfix for animals spawn

- CHANGELOG.md
- apps/client/src/app/pages/island-workshop/optimizer/planning-formula-optimizer.ts
- apps/client/src/environments/environment.ts
- apps/client/src/environments/patch-notes.ts
- package.json
> fix(island-workshop): fixed planning trying to compute result on first day

- .circleci/config.yml
> chore: update circleci windows orb

- CHANGELOG.md
- apps/client/src/app/+state/auth.effects.ts
- apps/client/src/app/core/database/user.service.ts
- apps/client/src/environments/patch-notes.ts
- package.json
> fix(auth): fixed new anonymous accounts reloading indefinitely

- apps/client/src/app/pages/island-workshop/workshop-planning/workshop-planning.component.html
Per LeitonGrey recommendation in discord.
> update IS research attribution

- apps/client/src/app/core/alarms/alarm-bell.service.ts
- apps/client/src/app/core/api/data.service.ts
- apps/client/src/environments/patch-notes.ts
- apps/electron/src/window/main-window.ts
> Desktop app hotfix

- apps/client/src/app/core/alarms/+state/alarms.facade.ts
- apps/client/src/app/core/alarms/alarm-bell.service.ts
- apps/client/src/app/pages/search/search-result/search-result.component.html
> chore(alarms): fix ring freezing the entire app

- .circleci/config.yml
> chore(CI): don't push tc-ssr cloud run, it's useless

- apps/api/src/app/search/search.controller.ts
- apps/api/src/app/search/search.service.ts
- apps/client/src/environments/patch-notes.ts
- tools/build/prod-assets-hash.js
> chore: better desktop app fix

- apps/client/src/app/pages/island-workshop/optimizer/planning-formula-optimizer.ts
Season 25, Rank 6, Cycle 6 as an example of the issue. Only occured with 4/4/4/4/4/4 schedules.
> fix(island-workshop): fixed planner sometimes using the same item twice in a row.

- apps/client/src/app/pages/island-workshop/optimizer/planning-formula-optimizer.ts
*84 schedules will either be 84, 484, or 8484 due to where this check is made, and this code covers all three.
> fix(island-workshop): fixed schedules ending in 84 when they occur

- apps/client/src/app/pages/simulator/components/simulator/simulator.component.html
- apps/client/src/app/pages/simulator/components/simulator/simulator.component.less
- apps/client/src/app/pages/simulator/components/simulator/simulator.component.ts
Adapted solution at https://github.com/angular/components/issues/13372#issuecomment-1264356365 to support lists outside the group.
> fix(simulator): actions sort in multi-row rotations now drags properly

- apps/client/src/app/core/eorzea/weather.service.ts
Avoid having max call stack exception on next weather time
> fix(safe-next-weather-transition): make safe the next diff weather time

- apps/client/src/assets/i18n/en.json
Removing unused keys from en.json
> chore(remove-deprecated-translation-keys): remove translations keys that are not used anymore

- apps/client/src/app/pages/island-workshop/island-workshop/island-workshop.component.ts
Some temporary console output for debugging if issues continue.
> fix(island-workshop): allowed better island state updating

- apps/client/src/app/pages/db/fish/fish-mooches/fish-mooches.component.html
- apps/client/src/app/pages/db/fish/fish-mooches/fish-mooches.component.less
- apps/client/src/app/pages/db/fish/fish-mooches/fish-mooches.component.ts
This PR fixes https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/2693
> fix(fish-mooches): fix mooches data loading feedback

- apps/client/src/app/pages/db/item/item.component.ts
This PR introduces a Saddlebag Exchange link to the item page.
> feat: added saddlebag link to item page

- apps/client/src/app/pages/currency-spending/currency-spending/currency-spending.component.ts
Adding Sil'dihn Potshred and Aloalo Pothserd on currency spending page
> feat(add-currency): add potshreds as currency spending

- apps/client/src/app/pages/macro-translator/macro-translator/macro-translator.component.ts
Fixing the mistranslation for FSH "Cast" skill.
> fix(macro-translator): Adding translation exception for FSH skill "Cast"

- README.md
Added wiki link to the README to increase project accessibility. See issue #2811
> docs(README): added a link to the project wiki

- apps/client/src/assets/i18n/en.json
This will hopefully clear up any confusion caused by the wording leading people to believe that TC is a solver and this button will spit out a rotation, while not affecting functionality.
> Change wording on generate macro button tooltip
